[package]
name = "ATOM-MATRIX-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
embedded-io = "0.6.1"
panic-abort = "0.3.2"

[dependencies.sh1107g-rs]
path = "../sh1107g-rs"
