
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]



[target.xtensa-esp32-none-elf]
runner = "esp espflash flash --release --monitor"

[env]
ESP_LOG="info"
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]